name: Build Site

on:
  push:
    branches: [ master ] 

env: 
  IMAGES_NAME: ${{github.repository}}

jobs:
  Build-and-Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup ruby
        uses: actions/setup-ruby@v1

      - name: Install Gems
        run:  bundle install

      - name: Build pages
        run: bundle exec jekyll build
     
      - name:  Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
     
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: jamesptanner/notes:latest
