name: Build Site

on:
  push:
    branches: [ master ] 

env: 
  IMAGES_NAME: ${{github.repository}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup ruby
        uses: actions/setup-ruby@v1

      - name: Cache Gems
        id: cache-gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Gems
        if: steps.cache-gems.outputs.cache-hit != 'true'
        run: |
          bundle config path vendor/bundle
          bundle install

      - name: Build pages
        run: bundle exec jekyll build

      - name: Stash artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pages
          path: _site

  package:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: pages

      - name: Build docker image
        run: docker build . --file dockerfile --tag notes:$(date +%s)

      - name:  Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: user/app:latest
