name: Build Site
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup ruby
        uses: actions/setup-ruby@v1

      - run: bundle install
      - name: Build pages
        run: bundle exec jekyll build